# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

stages:
  - stage: Build
    pool:
     name: Default
     demands: mycap
    jobs:   
      - job: Build
        

        variables:
           solution: '**/*.sln'
           buildPlatform: 'Any CPU'
           buildConfiguration: 'Release'
 
        steps:
        - task:  NuGetToolInstaller@1
        - task: NuGetCommand@2
          inputs:
            restoreSolution: '$(solution)'
        - task: VSBuild@1
          inputs:
           solution: '$(solution)'
           msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
           platform: '$(buildPlatform)'
           configuration: '$(buildConfiguration)'

        - script: echo 'Building application'
        - task: PublishBuildArtifacts@1
  - stage: Publish
    jobs:
       - job: Test
         pool:
          name: Default
          demands: mycap
        
         variables:
           solution: '**/*.sln'
           buildPlatform: 'Any CPU'
           buildConfiguration: 'Release'

         steps:
           - task: VSTest@2
             inputs:
              platform: '$(buildPlatform)'
              configuration: '$(buildConfiguration)'
           - script: echo 'Testing application'
           